# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(verbose_name=3)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
